Fix #112 Написана ViewModel для фрагмента Countries
zhebera/practicum-android-diploma pull request #115
Opened 2024-02-05 16:01 UTC by Jahnta

2024-02-05 19:15 UTC, HatePK approved these changes

2024-02-05 19:15 UTC, zhebera requested changes

2024-02-05 19:15 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesState.kt
> +    data class Error(
Ден, чтобы не было конфликтов, можешь класс Error без текста добавить, то есть просто object Error: CountriesState, потому что на этом экране плэйсхолдер будет показываться один и тот же вне зависимости от ошибки

2024-02-05 19:15 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesViewModel.kt
> +                    processResult(pair.first, pair.second)
Тут тогда можно убрать pair.second, если поменяешь Error

2024-02-05 19:15 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesViewModel.kt
> +            _countriesState.postValue(CountriesState.Error(message = message ?: "Неизвестная ошибка"))
а тут уже тоже не надо сообщение никакое

2024-02-06 07:34 UTC, Jahnta commented on app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesState.kt
> +    data class Error(
Мне кажется лучше оставить с текстом. Во-первых у нас из data слоя прокидывается текст, а во-вторых вдруг будет необходимость разные плэйлсхолдеры показывать?

2024-02-06 07:34 UTC, Jahnta commented on app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesViewModel.kt
> +                    processResult(pair.first, pair.second)
Предлагаю оставить, см. выше.

2024-02-06 07:34 UTC, Jahnta commented on app/src/main/java/ru/practicum/android/diploma/ui/countries/viewmodel/CountriesViewModel.kt
> +            _countriesState.postValue(CountriesState.Error(message = message ?: "Неизвестная ошибка"))
Предлагаю оставить, см. выше.

2024-02-06 08:10 UTC, zhebera approved these changes

2024-02-06 08:52 UTC, merged