epic6-errorStates-SearchFragment
zhebera/practicum-android-diploma pull request #166
Opened 2024-02-08 17:53 UTC by Averkieva

fix #54

2024-02-08 20:21 UTC, Jahnta reviewed
- При изменении текста и новом поиске RW - со старыми результатами поиска и количество результатов не пропадают (на заднем плане появляется progressbar)
- если не найдены вакансии должна быть другая заглушка

2024-02-09 07:03 UTC, HatePK approved these changes

2024-02-10 20:38 UTC, HatePK requested changes

2024-02-10 20:38 UTC, HatePK commented on app/src/main/res/layout/fragment_search.xml
> +        <TextView
RV накладывается на TV (достаточно просто поменять их местами в верстке)

![image](https://github.com/zhebera/practicum-android-diploma/assets/63811310/098618ea-688f-4120-83ab-c8b463cf17de)

2024-02-11 17:30 UTC, HatePK approved these changes

2024-02-12 09:09 UTC, merged