Fix#14
zhebera/practicum-android-diploma pull request #26
Opened 2024-01-22 20:35 UTC by Averkieva

fix #14

2024-01-22 21:19 UTC, void-85 approved these changes
проверил, нет замечаний

2024-01-23 03:28 UTC, HatePK approved these changes
Все норм вроде)

2024-01-23 08:14 UTC, zhebera requested changes

2024-01-23 08:14 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
> +            .baseUrl("https://api.hh.ru/")
Может лучше создать файл Consts в util, и вынести туда строковую переменную?

2024-01-23 08:14 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +            when {
С кодом все хорошо, но может отформатировать код, чтобы знак || разделял отдельные строки внутри when. Будет лучше для понимания.

2024-01-23 08:14 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/network/NetworkClient.kt
> +interface NetworkClient
Наверное, будет лучше сразу создать общий класс Response, который будет общим классом возвращения ответа от сервера, и внутрь интерфейса добавить одну функцию, по типу как мы делали в PlaylistMaker. 
Эта функция будет так же общим выходом для получения ответа от сервера.

2024-01-23 09:12 UTC, zhebera approved these changes
Критических замечаний нет.

2024-01-23 09:15 UTC, merged