Epic1 task37 searching api hh and realization
zhebera/practicum-android-diploma pull request #40
Opened 2024-01-25 14:58 UTC by zhebera

close #37

2024-01-26 12:59 UTC, Averkieva approved these changes

2024-01-26 12:59 UTC, Averkieva commented on app/src/main/java/ru/practicum/android/diploma/domain/impl/SearchInteractorImpl.kt
> +    override fun searchMovies(vacancy: String): Flow<Pair<Vacancies?, String?>> {
я бы наверное переименовала функцию)

2024-01-26 12:59 UTC, Averkieva commented on app/src/main/java/ru/practicum/android/diploma/domain/api/search/SearchInteractor.kt
> +    fun searchMovies(vacancy: String): Flow<Pair<Vacancies?, String?>>
ну и тут наверное тоже стоит переименовать

2024-01-26 12:59 UTC, Averkieva commented on app/src/main/java/ru/practicum/android/diploma/data/search/SearchRepositoryImpl.kt
> +                emit(Resource.Error("Проверьте подключение к интернету"))
наверное стоит добавить это в строковые ресурсы

2024-01-26 12:59 UTC, Averkieva commented on app/src/main/java/ru/practicum/android/diploma/data/search/SearchRepositoryImpl.kt
> +            else -> emit(Resource.Error("Ошибка сервера"))
тут тоже

2024-01-26 21:16 UTC, HatePK requested changes

2024-01-26 21:16 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/data/response/VacanciesResponse.kt
> +class VacanciesResponse(
Возможно правильнее сделать эти классы data

2024-01-26 21:16 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/data/response/VacanciesResponse.kt
> +    @SerializedName("alternate_url") val alternateUrl: String,
Может быть null

2024-01-26 21:16 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/data/response/VacanciesResponse.kt
> +    val id: String,
Может быть null

2024-01-26 21:16 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/data/response/VacanciesResponse.kt
> +    @SerializedName("logo_urls") val logoUrls: LogoUrlsResponse,
Далее ниже аналогично: многие поля в hh api не помечены как required, может прийти null

2024-01-26 21:16 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt
> +        if (data.found == 0) {
В такой проверке нет необходимости, если результат SUCCESS, то там всегда будут какие-то вакансии.

2024-01-26 21:16 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt
> +            _searchState.postValue(SearchState.Error(message ?: "Unknown error"))
Можно тоже в ресурсы добавить

2024-01-27 10:31 UTC, HatePK approved these changes

2024-01-28 07:12 UTC, merged