Epic2 task41 vacancy details search request
zhebera/practicum-android-diploma pull request #48
Opened 2024-01-27 12:46 UTC by Jahnta

Fix №41
Реализована логика получения деталей необходимой вакансии, создана тестовая кнопка на экране поиска

2024-01-27 17:26 UTC, HatePK approved these changes

2024-01-29 09:47 UTC, zhebera requested changes
Все круто, только небольшие замечания, пометил в комментариях)

2024-01-29 09:47 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/converters/VacanciesConverter.kt
> +
Лучше переименовать конвертер в VacancyDescriptionConverter, дабы избежать путаницы в нейминге

2024-01-29 09:47 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/converters/VacanciesConverter.kt
> +
Может имеет смысл вынести функционал в отдельный класс, например, VacancyDescriptionConverter, дабы не кидать все в один файл и класс

2024-01-29 09:47 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +        binding.testButton.setOnClickListener {
Думаю, что эту строку лучше убрать, так как она используется для теста, так что в результат лучше не брать это

2024-01-29 09:47 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/VacancyDescriptionFragment.kt
> +        viewModel.getVacancyDescription("88114733")
Лучше сразу договриться с комнадой по разработке о том, как будут передаваться данные в этот фрагмент)

2024-01-29 09:47 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/VacancyDescriptionFragment.kt
> +        binding.textView
Лучше убрать)

2024-01-29 14:36 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/VacancyDescriptionFragment.kt
> +        viewModel.getVacancyDescription("88114733")
Привет, работа во фрагменте не в рамках текущей задачи, так что лучше сейчас просто удалить лишнюю логику.

2024-01-30 08:10 UTC, zhebera approved these changes
Критических замечаний нет

2024-01-30 08:18 UTC, merged