Fix#38
zhebera/practicum-android-diploma pull request #49
Opened 2024-01-28 22:17 UTC by Averkieva

fix #38

2024-01-29 06:19 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}
Пустые блоки он предлагает всегда удалять за ненадобностью

2024-01-29 06:19 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +            override fun afterTextChanged(s: Editable?) {}
Тут так же

2024-01-29 06:27 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +    private lateinit var recyclerView: RecyclerView
Предлагает использовать не lateinit, а занулять переменную, а потом уже инициализировать дальше

2024-01-29 06:28 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/details/DetailsFragment.kt
> +import ru.practicum.android.diploma.databinding.FragmentDetailsBinding
Тут он говорит, что импорт должен идти по алфавиту и без использования *

2024-01-29 06:30 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/search/SearchRepositoryImpl.kt
> +        if (json != null && json.isNotEmpty()) {
Тут скорее всего он говорит разделить один if на два последовательных, типа 
if(json != null){
   if(json.isNotEmpty())
}

Да и у строки есть функция isNotNullOrEmpty(), лучше использовать для читабельности кода

2024-01-29 08:01 UTC, zhebera requested changes
Нужно кое-что поправить

2024-01-29 08:01 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/viewmodel/SearchViewModel.kt
> +        private const val SEARCH_DEBOUNCE_DELAY = 1000L
По заданию, кажется, было 2 секунды

2024-01-29 10:19 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +        val navController = findNavController()
Можно напрямую вызывать через fndNavController

2024-01-29 10:21 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/search/SearchRepositoryImpl.kt
> +    private var vacancies = ArrayList<Vacancy>()
Может это тоже убрать?

2024-01-29 10:21 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/data/search/SearchRepositoryImpl.kt
> +    private val gson: Gson
Эти зависимости сейчас не нужны, поэтому, думаю, можно тоже убрать

2024-01-29 10:22 UTC, zhebera commented on app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
> +
Тоже пока нет необходимости в этом...

2024-01-29 14:28 UTC, HatePK requested changes
Немного нелогично, на мой взгляд, работает строка поиска

2024-01-29 14:28 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +                binding.ivSearchImage.setImageResource(R.drawable.search)
Сейчас при нажатии на крестик, кнопка полностью исчезает, вместо нее не появляется "поиск". 

Кроме того, выполняется запрос с введенным текстом

2024-01-29 14:28 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +                if (!s.isNullOrEmpty()) {
при удалении символов, с пустой строкой отправляется запрос

2024-01-29 14:28 UTC, HatePK commented on app/src/main/java/ru/practicum/android/diploma/ui/search/fragment/SearchFragment.kt
> +                vacancyAdapter.clear()
Нужно ли очищать адаптер каждый раз при нажатии на крестик?

2024-01-30 12:02 UTC, zhebera approved these changes

2024-01-30 12:04 UTC, merged