Fix#63
zhebera/practicum-android-diploma pull request #64
Opened 2024-02-01 22:43 UTC by Averkieva

fix #63

2024-02-02 14:47 UTC, HatePK requested changes

2024-02-02 14:47 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +            android:src="@drawable/arrow_back" />
Получилось не по макету: кнопка должна быть 48х48 dp. Размер картинки 24x24, паддинги должны быть по 12dp (вместо 8). 

![Снимок](https://github.com/zhebera/practicum-android-diploma/assets/63811310/ee4b036e-d0b1-4ad8-959d-63528e96b94b)

2024-02-02 14:47 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +    </com.google.android.material.textfield.TextInputLayout>
Можно реализовать это гораздо проще:

У Filled text field, которые ты тут используешь, есть встроенная иконка Trailing icon:

![image](https://github.com/zhebera/practicum-android-diploma/assets/63811310/a21c4c61-2edb-4a71-9be5-b96244662a3f)

Ей можно задавать любой drawable с помощью атрибута app:endIconDrawable

А во фрагменте мы сможем менять эту иконку с помощью метода setEndIconDrawable (когда будет выбрано место работы и отрасль)

Подробнее здесь: https://m2.material.io/components/text-fields/android#filled-text-field

2024-02-02 14:47 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +        app:layout_constraintVertical_bias="1.0" />
Если получится задать Trailing icon, то эти два imageView не нужны

2024-02-02 14:47 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +    <EditText
Здесь тоже нужно использовать Filled text field: https://m2.material.io/components/text-fields/android#filled-text-field

2024-02-02 14:47 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +        android:id="@+id/tv_expected_salary"
Если получится, то этот textView не нужен

2024-02-02 14:47 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +        app:layout_constraintVertical_bias="0.448" />
Лишняя строчка, кажется

2024-02-03 13:02 UTC, zhebera requested changes
Согласен с замечаниями @HatePK

2024-02-03 14:29 UTC, Jahnta approved these changes

2024-02-03 15:24 UTC, HatePK approved these changes

2024-02-03 15:24 UTC, HatePK commented on app/src/main/res/layout/fragment_filter.xml
> +        <ImageView
У кнопки есть небольшой отступ 4dp слева

2024-02-03 17:02 UTC, merged