Fix#67
zhebera/practicum-android-diploma pull request #68
Opened 2024-02-02 09:59 UTC by Averkieva

fix #67

2024-02-02 15:17 UTC, HatePK requested changes

2024-02-02 15:17 UTC, HatePK commented on app/src/main/res/layout/fragment_filter_place_of_work.xml
> +            android:paddingStart="@dimen/fragment_filter_place_of_work_padding_start"
То же самое, что в https://github.com/zhebera/practicum-android-diploma/pull/64

1) Этот paddingStart не нужен
2) LinearLayout нужно привязать к parent, а не к guidline. Убрать ему marginStart и задать паддинги согласно макету: 4dp на start и 8dp на End
3) Увеличить общие паддинги у этой кнопки до 12dp (вместо 8dp) согласно макету.

2024-02-02 15:17 UTC, HatePK commented on app/src/main/res/layout/fragment_filter_place_of_work.xml
> +    <com.google.android.material.textfield.TextInputLayout
Аналогично из предыдущего ПР: https://github.com/zhebera/practicum-android-diploma/pull/64#discussion_r1476122873

Можно задать Trailing icon, вместо того чтобы использовать два лишних ImageView

2024-02-03 14:33 UTC, Jahnta approved these changes

2024-02-03 15:30 UTC, HatePK approved these changes

2024-02-03 15:30 UTC, HatePK commented on app/src/main/res/layout/fragment_filter_place_of_work.xml
> +            android:padding="@dimen/fragment_filter_place_of_work_padding"
12dp, а не 8. 

И тогда нужно исправить родительский LinearLayout ll_main_text: лучше задать ему фиксированную высоту 64dp, а paddingVertical убрать совсем.

2024-02-03 17:28 UTC, merged