Fix#70
zhebera/practicum-android-diploma pull request #71
Opened 2024-02-02 11:38 UTC by Averkieva

fix #70

2024-02-02 15:26 UTC, HatePK requested changes

2024-02-02 15:26 UTC, HatePK commented on app/src/main/res/layout/fragment_filter_country.xml
> +            android:paddingStart="@dimen/fragment_filter_country_padding_start"
Аналогично: https://github.com/zhebera/practicum-android-diploma/pull/68#discussion_r1476186525

2024-02-02 15:26 UTC, HatePK commented on app/src/main/res/layout/fragment_filter_country.xml
> +        tools:text="@string/no_such_region" />
Лучше сложить картинку и текст об ошибке в общий контейнер, чтобы управлять видимостью этого контейнера одной строчкой кода

2024-02-03 14:34 UTC, Jahnta approved these changes

2024-02-03 16:26 UTC, HatePK approved these changes

2024-02-03 19:06 UTC, merged